version: '3.1'

services:

  wordpress:
    container_name: docker_my_wordpress
    image: wordpress:php7.2
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      WORDPRESS_DB_PASSWORD: 123456
    volumes:
      - ../wordpress:/var/www/html

  mysql:
    container_name: docker_my_mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ../mysql:/var/lib/mysql
